# Generated by Django 3.2.6 on 2021-09-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210901_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pots',
            field=models.ManyToManyField(to='main_app.Pot'),
        ),
    ]
